# -*- coding: utf-8 -*-
{
    "name": "Liquidación de Gastos y Ventas",
    "version": "19.0.1.1.0",
    "category": "Accounting/Accounting",
    "summary": "Settlement workflow for purchases AND sales: staging, multi-level approval, automatic journal entries, payment/collection wizard and KPI dashboard",
    "description": "Flujo completo de liquidacion de gastos (compras) y ventas: staging por clase, aprobacion multinivel, asientos automaticos (por pagar / por cobrar), asistente de pago o cobro y dashboard.",
    "author": "KONTAXES",
    "website": "https://www.kontaxes.com",
    "license": "OPL-1",
    "price": 0.0,
    "currency": "USD",
    "depends": [
        "account",
        "mail",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "report/settlement_report.xml",
        "views/settlement_staging_views.xml",
        "views/settlement_views.xml",
        "views/settlement_payment_wizard_views.xml",
        "views/settlement_reject_wizard_views.xml",
        "views/staging_selection_wizard_views.xml",
        "views/assign_settlement_wizard_views.xml",
        "views/account_move_views.xml",
        "views/res_config_settings_views.xml",
        "views/dashboard_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "images": [
        "static/description/banner.gif",
        "static/description/banner.png",
    ],
    "web_icon": "ktx_expense_management,static/description/icon.png",
}
