# -*- coding: utf-8 -*-
{
    "name": "Caja Chica",
    "version": "19.0.2.0.6",
    "category": "Accounting/Accounting",
    "summary": "Fondos de caja chica con gráficos configurables, integración contable, asientos automáticos y cierres mensuales",
    "description": "Gestion de fondos de caja chica con flujo de aprobacion, integracion contable, reposiciones y cierres mensuales.",
    "author": "KONTAXES",
    "website": "https://app.kontaxes.com",
    "license": "OPL-1",
    "price": 20.00,
    "currency": "USD",
    "depends": ["account", "mail"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "report/petty_cash_report.xml",
        "views/petty_cash_fund_views.xml",
        "views/petty_cash_move_views.xml",
        "views/petty_cash_replenishment_views.xml",
        "views/petty_cash_reject_wizard_views.xml",
        "views/petty_cash_closing_wizard_views.xml",
        "views/petty_cash_staging_views.xml",
        "views/petty_cash_assign_wizard_views.xml",
        "views/petty_cash_fund_replenishment_wizard_views.xml",
        "views/petty_cash_add_expense_wizard_views.xml",
        "views/petty_cash_reimburse_wizard_views.xml",
        "views/account_move_views.xml",
        "views/petty_cash_config_settings_views.xml",
        "views/dashboard_views.xml",
        "views/menus.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
    "images": [
        "static/description/banner.gif",
        "static/description/banner.png",
    ],
    "web_icon": "ktx_petty_cash,static/description/icon.png",
}
